
[build]
  publish = "."
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "nodemailer", "node-fetch", "mongodb"]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/confirm"
  to = "/.netlify/functions/confirm"
  status = 200

